server:
  port: 8084

spring:
  application:
    name: order-query
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/order_query?authSource=admin

logging:
  level:
    org:
      springframework.data.mongodb.core: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/