server:
  port: 8080

spring:
  application:
    name: server1

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
  h2:
    console:
      enabled: true
      path: /h2-console