server:
  port: 8080

spring:
  application:
    name: server1

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
  h2:
    console:
      enabled: true
      path: /h2-console

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    virtual-host: /

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health, info
  metrics:
    tags:
      application: ${spring.application.name}