server:
  port: 8082

spring:
#  # H2 Database ??
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: 'jdbc:h2:mem:test'
#
#  # H2 Console ??
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/product_service
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace