server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: member
          uri: lb://MEMBER
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret:
    key: aajdtrhyergrdjcftjftgxehrdhxdrehxdrjxdrgfes

springdoc:
  swagger-ui:
    use-root-path: true
    urls:
      - name: 회원 서비스
        url: /member/api-docs
    operationsSorter: method
    displayRequestDuration: true
