server:
  port: 8000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5173"
              - "https://localhost:5173"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

#      routes:
#        - id: collector
#          uri: lb://COLLECTOR
#          predicates:
#            - Path=/collector/**
#          filters:
#            - StripPrefix=1

# todo: swagger 통합 설정

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}