spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
    datasource:
      url: jdbc:postgresql://localhost:5432/test
      username: postgres123
      password: postgres123

  h2:
    console:
      enabled: true
      path: /h2-console