version: '3.8'

services:
  app1:
    container_name: app1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8080"
    volumes:
      - ./scouter:/scouter
    networks:
      - mirero

networks:
  mirero:
    driver: bridge