server:
  port: 0

spring:
  application:
    name: member

  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL}

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

